### ISSUE TITLE
Features not appearing on MapCampaigner that exist in OSM

### ISSUE THREAD

**Issue by jessbeutler** [hotosm/MapCampaigner#706] opened 2019-07-30 00:01 UTC
May be related to #686  

Features pulled do not appear to match those available in OSM. In this [case](https://campaigns.hotosm.org/campaign/1283c18117e245f6b4808c845096d582), buildings do not match the basemap or what exists in OSM. 

Comparison between Campaigner & JOSM for same area:

![image](https://user-images.githubusercontent.com/36767434/62090611-9c809d80-b23b-11e9-8d44-f60944ca691a.png)

![image](https://user-images.githubusercontent.com/36767434/62090553-62af9700-b23b-11e9-980b-cd0c86293587.png)

**Comment by jessbeutler** [comment] 2019-07-30 17:28
Also possibly related - or separate issue:

Point features in this [campaign](https://campaigns.hotosm.org/campaign/9d4b1001bdfd40e9abc9e1b38dc4400b) are not rendering for some features: 

![image](https://user-images.githubusercontent.com/36767434/62150809-ea91b180-b2cc-11e9-8472-09935597339f.png)

![image](https://user-images.githubusercontent.com/36767434/62150871-11e87e80-b2cd-11e9-9901-7813d1061b5e.png)

But is rendering for others:
![image](https://user-images.githubusercontent.com/36767434/62150968-43f9e080-b2cd-11e9-829b-f2de05effb0c.png)

**Comment by willemarcel** [comment] 2019-07-31 11:09
@jessbeutler @smit1678 some discoveries:

About buildings on [1283c18117e245f6b4808c845096d582](https://campaigns.hotosm.org/campaign/1283c18117e245f6b4808c845096d582), overpass is downloading the correct data, but we are losing features on the conversion to geojson. I downloaded the geojson from S3 and it has the same data as the vector tiles. I executed the functions again to that campaign and the result was the same. @JorgeMartinezG could you take a look on it or remember me the part of the code that makes the conversion to GeoJSON?

About the highways on [9d4b1001bdfd40e9abc9e1b38dc4400b](https://campaigns.hotosm.org/campaign/9d4b1001bdfd40e9abc9e1b38dc4400b), the problem is the query is set to `"highway"~"secondary"`, it should be only `"highway"` to return all the highways.
On the same campaign, it was missing the vector tiles for `Solid_Waste_-_Toilets` type. I processed it.

**Comment by jessbeutler** [comment] 2019-07-31 14:01
Thanks @willemarcel! Re: highways - oops! I was playing with the tagging to work around that error message I had been getting and forgot reset the proper highway tag. All is working for highways and toilets now.

**Comment by russbiggs** [comment] 2019-10-21 20:35
fixed in #733

**Closed by russbiggs** 2019-10-21 20:35 UTC
Labels: Component: Back End, Type: Bug
